using static GlobalEnums;
using System.Collections.Generic;

/// <summary>
/// Represents the rewards earned from completing a room in the tower system.
/// </summary>
/// <remarks>
/// Dependencies and Usage:
/// - Used by: RewardCalculator, RoomManager, TowerProgressionTests
/// - Related Systems: Tower system, Progression system, Inventory system
/// - Configuration: Uses RewardConfig for tier chances and base quantities
/// - Data Flow: Generated by RewardCalculator and consumed by progression/inventory systems
/// 
/// This class encapsulates both experience points and tiered item rewards that a player
/// can earn from completing rooms in the tower. The rewards are calculated based on:
/// - Room type (Boss, MiniBoss, Standard)
/// - Floor number
/// - Character level and stats
/// - Room difficulty
/// </remarks>
public partial class RoomReward
{
    /// <summary>
    /// Gets or sets the amount of experience points earned from completing the room.
    /// The experience value is affected by room type, floor level, and character stats.
    /// </summary>
    public float Experience { get; set; }

    /// <summary>
    /// Gets or sets the list of item rewards earned from completing the room.
    /// Each reward consists of a tier (Common, Rare, Epic, etc.) and a quantity.
    /// The rewards are generated based on room difficulty and floor progression.
    /// </summary>
    /// <remarks>
    /// The reward tiers are determined by probability tables in RewardConfig,
    /// with higher floor numbers increasing the chances of better reward tiers.
    /// </remarks>
    public List<(RewardTier tier, int quantity)> Rewards { get; set; } = new();
}
